// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiwwuydffemkzofdlxif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpd3d1eWRmZmVta3pvZmRseGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDIyNDQsImV4cCI6MjA3NDExODI0NH0.y6atQqm9zN8PvITS0bnJKwHu6GOlPpZLR2RGm3um3_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});